name: IMSDK_UAT_Compilation
run-name: "${{ github.event_name == 'pull_request' && format('IMSDK UAT Compilation: #{0}', github.event.pull_request.number) || '' }}"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      sdk-url: ${{ steps.sdk-url.outputs.sdk-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Resolve SDK URL from latest wrynose nightly
        id: sdk-url
        uses: ./.github/actions/resolve-nightly-download-url
        with:
          token: ${{ secrets.QUALCOMM_LINUX_PAT }}

      - name: Print Build Urls
        run: |
          echo "Resolved SDK and image URLs from latest wrynose nightly:"
          echo "SDK URL: ${{ steps.sdk-url.outputs.sdk-url }}"
          echo "iq-9075-evk/proprietary: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-9075-evk/proprietary'] }}"
          echo "iq-9075-evk/multimedia: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-9075-evk/multimedia'] }}"
          echo "iq-8275-evk/proprietary: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-8275-evk/proprietary'] }}"
          echo "iq-8275-evk/multimedia: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-8275-evk/multimedia'] }}"
          echo "iq-615-evk/proprietary: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-615-evk/proprietary'] }}"
          echo "iq-615-evk/multimedia: ${{ fromJson(steps.sdk-url.outputs.image-urls)['iq-615-evk/multimedia'] }}"
          echo "rb3gen2-core-kit/proprietary: ${{ fromJson(steps.sdk-url.outputs.image-urls)['rb3gen2-core-kit/proprietary'] }}"
          echo "rb3gen2-core-kit/multimedia: ${{ fromJson(steps.sdk-url.outputs.image-urls)['rb3gen2-core-kit/multimedia'] }}"
  build:
    needs: init
    runs-on:
      group: GHA-Framework-Stg-SelfHosted-RG
      labels:
        - self-hosted
        - framework-stg-u2404-x64-od-ephem

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run build
        env:
          S3_WEBAPP_TOKEN: ${{ secrets.S3_WEBAPP_TOKEN }}
          SDK_OBJECT_URL: ${{ needs.init.outputs.sdk-url }}
        run: |
          chmod +x ci/build.sh
          ./ci/build.sh
      
      - name: Prepare upload directory
        run: |
          mkdir -p upload_dir
          mv imsdk-artifacts.tar.gz upload_dir/

      - name: Upload artifacts to S3 bucket
        uses: qualcomm-linux/upload-private-artifact-action@aws-v4
        with:
          path: ${{github.workspace}}/upload_dir
          destination: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}/
          s3_bucket: qli-stg-framework-gh-artifacts
